MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure

Instructions/Labs/AZ-203_02_lab.md, Instructions/Labs/AZ-203_02_lab_ak.md, Instructions/Labs/AZ-203_03_lab.md, Instructions/Labs/AZ-203_03_lab_ak.md, Instructions/Labs/AZ-203_04_lab.md, Instructions/Labs/AZ-203_04_lab_ak.md, Instructions/Labs/AZ-203_05_lab.md, Instructions/Labs/AZ-203_05_lab_ak.md, Instructions/Labs/AZ-203_06_lab.md, Instructions/Labs/AZ-203_06_lab_ak.md
- Updated lab instructions to point to the correct GitHub repository name
=> Updated Lab Instructions

Instructions/Labs/AZ-203_01_lab.md
Fixes # .
- There are 2 typos in the Azure CLI commands, this PR fixes them
=> Fixed typo in AZ-203_01_lab.md

Instructions/Labs/AZ-203_06_lab.md
Fixes 3 instructions where "inbound" should have been "outbound"
=> T06 - inbound should be outbound in Ex3 Task3

Instructions/Labs/AZ-203_01_lab.md, Instructions/Labs/AZ-203_01_lab_ak.md, Instructions/Labs/AZ-203_02_lab.md, Instructions/Labs/AZ-203_02_lab_ak.md, Instructions/Labs/AZ-203_03_lab.md, Instructions/Labs/AZ-203_03_lab_ak.md, Instructions/Labs/AZ-203_04_lab.md, Instructions/Labs/AZ-203_04_lab_ak.md, Instructions/Labs/AZ-203_05_lab.md, Instructions/Labs/AZ-203_05_lab_ak.md, Instructions/Labs/AZ-203_06_lab.md, Instructions/Labs/AZ-203_06_lab_ak.md
-Converted labs to markdown
-Updated instructions to reflect changes in Azure
=> Corrected the markdown on answerkeys

Instructions/Labs/AZ-203_01_lab.md
=> Fix Ubuntu typo

Instructions/Labs/AZ-203_06_lab.md, Instructions/Labs/AZ-203_06_lab_ak.md
=> some minor cleanup on early steps

Instructions/Labs/AZ-203_01_lab_ak.md
- Course: 00
- Exercise: 00
- Task: 00
- Step[s]: 00
-
-
-
=> Several clarifications and additions

Instructions/Labs/AZ-203_04_lab_ak.md
- Course: T04
- Exercise: 01
- Task: 04
- Step[s]: 06-vii
- Renamed **Runtime Stack** option from **.NET** to **.NET Core**
=> Fixed Function App Runtime Stack option

Instructions/Labs/AZ-203_03_lab.md
- Course: 00
- Exercise: 00
- Task: 00
- Step[s]: 00
-
-
-
=> Updated AZ-203_03_lab.md

Instructions/Labs/AZ-203_01_lab.md
- Course: 00
- Exercise: 02
- Task: 02
- Step[s]:4 y 11
- Username
- typo 
-
=> Fix username and a typo

Instructions/Labs/AZ-203_03_lab.md, Instructions/Labs/AZ-203_03_lab_ak.md
- Course: AZ-203 Lab 03: Lab: Constructing a polyglot data solution
- Exercise: 04
- Task: 01
- Step[s]: 08
- Fix bug reported in #74 
- Updated Answer Key to match upserted code string in high-level instructions
=> Patched langVersion issue

Instructions/Labs/AZ-203_04_lab_ak.md
Several minor changes have been made to the Azure screens for adding new Access Policies that impact the answer key.
Several back slashes occur in sample code that are not needed.
- Course: AZ-203_04A
- Exercise: 02-04
- Task: several
- Step[s]: several
-
-
-
=> AZ-203_04_lab_ak.md - step changes and code clearnup

Instructions/Labs/AZ-203_02_lab_ak.md
Corrects issue #81 - please refer to that for more information.  Should be validated before acceptance.
=> Correct issue #81 in this version of 203.2

Instructions/Labs/AZ-203_03_lab.md
=> Address #81 in 203.3 non-AK

Instructions/Labs/AZ-203_03_lab_ak.md
=> Address #81 in 203.3 AK

Instructions/Labs/AZ-203_04_lab.md
=> Address #81 in 203.4 Non-AK

Instructions/Labs/AZ-203_03_lab_ak.md
- Course: 03
- Exercise: 03
- Task: 01
- Step[s]: 03
- `(F):\Allfiles\03\Starter\AdventureWorks` -> `(F):\Allfiles\Labs\03\Starter\AdventureWorks`
=> Fix AZ-203_03_lab_ak.md Exercise3 Task1 file path

Instructions/Labs/AZ-203_01_lab.md, Instructions/Labs/AZ-203_01_lab_ak.md, Instructions/Labs/AZ-203_02_lab.md, Instructions/Labs/AZ-203_02_lab_ak.md, Instructions/Labs/AZ-203_03_lab.md, Instructions/Labs/AZ-203_03_lab_ak.md, Instructions/Labs/AZ-203_04_lab.md, Instructions/Labs/AZ-203_04_lab_ak.md, Instructions/Labs/AZ-203_05_lab.md, Instructions/Labs/AZ-203_05_lab_ak.md, Instructions/Labs/AZ-203_06_lab.md, Instructions/Labs/AZ-203_06_lab_ak.md
This will help improve the readability of the code blocks ;)
=> Enable syntax highlight in Instructions code blocks

Allfiles/Labs/03/Solution/AdventureWorks/AdventureWorks.Web/Properties/launchSettings.json, Allfiles/Labs/03/Starter/AdventureWorks/AdventureWorks.Web/Properties/launchSettings.json, Instructions/Labs/AZ-203_01_lab.md, Instructions/Labs/AZ-203_01_lab_ak.md, Instructions/Labs/AZ-203_02_lab.md, Instructions/Labs/AZ-203_02_lab_ak.md, Instructions/Labs/AZ-203_03_lab.md, Instructions/Labs/AZ-203_03_lab_ak.md, Instructions/Labs/AZ-203_04_lab.md, Instructions/Labs/AZ-203_04_lab_ak.md, Instructions/Labs/AZ-203_05_lab.md, Instructions/Labs/AZ-203_05_lab_ak.md, Instructions/Labs/AZ-203_06_lab.md, Instructions/Labs/AZ-203_06_lab_ak.md, index.md
- Remove unnecessary trailing spaces
=> Remove unnecessary trailing spaces

Instructions/Labs/AZ-203_06_lab.md, Instructions/Labs/AZ-203_06_lab_ak.md
=> change order for create and use resource group

Instructions/Labs/AZ-203_06_lab_ak.md
Azure Search is renamed by Azure Cognitive Search
- Course: 06
- Exercise: 01
- Task: 03
- Step[s]: 04
Replaced Azure Search by Azure Cognitive Search
-
-
-
=> Azure Cognitive Search

Instructions/Labs/AZ-203_03_lab.md
- Course: AZ203-03
- Exercise: 05
- Task: 02, 5
Clean up of extra code snippet decorators.
=> Clean code snippets - Lab 03 - Exercise 5

Instructions/Labs/AZ-203_05_lab_ak.md
Select a resource is replaced by select a scope
- Course: 05
- Exercise: 04
- Task: 02
- Step[s]: 04i
-Select a scope instead of select a resource
-
-
=> Select a scope for metrics

Instructions/Labs/AZ-203_06_lab_ak.md
- Course: 06
- Exercise: 01
- Task: 04
- Step[s]: 6~9
- Remove additional "+ Add field"
Those "+ Add field" seem wrong to me but please also confirm that before merging.
=> Remove duplicated "+ Add field" action in AZ-203_06_lab_ak.md

Instructions/Labs/AZ-203_05_lab_ak.md
This was probably copied & pasted from one of the previous tasks
=> Remove unnecessary step

Instructions/Labs/AZ-203_03_lab.md
there were a few commands with wrong code formatting hints (using language name both before and after the snippet)
- Course: AZ203
- Exercise: 6
- Task: 2
- Step[s]: 10
- Course: AZ203
- Exercise: 6
- Task: 5
- Step[s]: 1
- Just fixed some formatting issue
-
-
=> Fixed a few formatting issues

Instructions/Labs/AZ-203_03_lab.md
The current code uses a Mock service, not a SQL database.
- Course: AZ203
- Exercise: 6
- Task: 4
- Step[s]: 2
-
-
-
=> Fixed note about checkout service
